export const STATUS_LABELS: Record<string, string> = {
    // Processo de registro e CRM
    WAITING_CONTRACT: 'Aguardando contrato',
    WAITING_SIGNATURE: 'Aguardando assinatura',
    WAITING_PAYMENT: 'Aguardando pagamento',
    WAITING_DOCS: 'Aguardando documentos',
    WAITING_DOCUMENTS: 'Aguardando documentos',
    WAITING_GRU: 'Aguardando pagamento da GRU',
    READY_TO_FILE: 'Pronto para protocolar',
    NEW: 'Em preparação',
    STARTED: 'Processo iniciado',
    LEADS: 'Novo lead',
    CONTATO_INICIADO: 'Contato iniciado',
    EM_CONVERSA: 'Em conversa',
    PREPARATION: 'Preparação',
    VIABILITY: 'Viabilidade',
    PROPOSTA: 'Proposta',
    CONTRACT: 'Contrato',
    CONTRACT_SIGNED: 'Contrato assinado',
    SERVICE_PAYMENT: 'Pagamento do serviço',
    DOCUMENTATION: 'Procuração e documentos',
    FEDERAL_FEE: 'Taxa federal (GRU)',
    FILED: 'Protocolado no INPI',
    PROTOCOL: 'Protocolo realizado',
    EXAMINATION: 'Exame de mérito',
    EXAM_MERIT: 'Exame de mérito',
    OPPOSITION: 'Oposição ou exigência',
    GRANTED: 'Deferido',
    DENIED: 'Indeferido',
    WON: 'Concluído',
    ARCHIVED: 'Arquivado',

    // Pagamentos, documentos e assinaturas
    AWAITING_PAYMENT_METHOD: 'Aguardando forma de pagamento',
    INITIAL_PAYMENT_PENDING: 'Primeira cobrança em processamento',
    PAYMENT_METHOD_UPDATING: 'Atualizando forma de pagamento',
    PAYMENT_RECOVERY_PENDING: 'Regularização em processamento',
    PAYMENT_FAILED: 'Pagamento pendente',
    PAYMENT_REVERSED: 'Pagamento estornado',
    RECEIPT_UPLOADED: 'Comprovante em análise',
    WAITING_VALIDATION: 'Aguardando validação',
    UPLOADED: 'Enviado',
    SENT: 'Enviado',
    SIGNED: 'Assinado',
    VALIDATED: 'Validado',
    APPROVED: 'Aprovado',
    AUTHORIZED: 'Autorizada',
    PAID: 'Pago',
    RECEIVED: 'Recebido',
    RECEIVED_IN_CASH: 'Recebido em dinheiro',
    CONFIRMED: 'Confirmado',
    OVERDUE: 'Vencido',
    REFUSED: 'Recusado',
    REFUNDED: 'Estornado',
    CREATING: 'Gerando cobrança',

    // Assinaturas e recorrência
    ACTIVE: 'Ativo',
    CREATED: 'Aguardando autorização',
    PENDING_SETUP: 'Em configuração',
    SETTING_UP: 'Em configuração',
    REAUTHORIZATION_PENDING: 'Aguardando nova autorização',
    SETUP_FAILED: 'Configuração incompleta',
    SETUP_REQUIRES_REVIEW: 'Conciliação necessária',

    // Processamentos e integrações
    PENDING: 'Pendente',
    WAITING: 'Aguardando',
    QUEUED: 'Na fila',
    PROCESSING: 'Processando',
    PROCESSED: 'Processado',
    RUNNING: 'Em execução',
    IMPORTING: 'Importando',
    READY: 'Pronto para ativar',
    COMPLETED: 'Concluído',
    COMPLETED_PARTIAL: 'Concluído parcialmente',
    COMPLETED_WITH_ERRORS: 'Concluído com alertas',
    COMPLETED_WITH_BUDGET_LIMIT: 'Concluído no limite de uso',
    SUCCEEDED: 'Concluído com sucesso',
    SUCCESS: 'Concluído com sucesso',
    FAILED: 'Falhou',
    ERROR: 'Erro',
    CANCELLED: 'Cancelado',
    CANCELED: 'Cancelado',
    SKIPPED: 'Não necessário',
    PAUSED: 'Pausado',
    DISABLED: 'Desativado',
    ENABLED: 'Ativo',
    INACTIVE: 'Inativo',
    ONLINE: 'Online',
    OFFLINE: 'Offline',
    AWAY: 'Ausente',
    BUSY: 'Ocupado',
    OPERATIONAL: 'Operacional',
    DEGRADED: 'Funcionamento parcial',
    BLOCKED: 'Bloqueado',
    BANNED: 'Banido',
    SUSPENDED: 'Suspenso',
    PUBLISHED: 'Publicado',
    RESOLVED: 'Resolvido',
    VERIFIED: 'Verificado',
    OPEN: 'Aberto',
    CLOSED: 'Encerrado',
    TODO: 'A fazer',
    BACKLOG: 'Aguardando priorização',
    IN_PROGRESS: 'Em andamento',
    DONE: 'Concluído',
    CONNECTED: 'Conectado',
    DISCONNECTED: 'Desconectado',
    MISCONFIGURED: 'Configuração incompleta',
    OCCUPIED: 'Ocupado',
    VACANT: 'Disponível',
    MAINTENANCE: 'Em manutenção',
    EXPIRED: 'Expirado',
    CHURN: 'Cliente perdido',
    LEAD: 'Potencial cliente',
    AT_RISK: 'Em risco',
    DELAYED: 'Atrasado',
    LOADING: 'Carregando',
    PAST: 'Encerrado',
    NOW: 'Em andamento',
    FUTURE: 'Agendado',
    DRAFT: 'Rascunho',
    SUPERSEDED: 'Substituído por uma versão mais recente',
    ROLLED_BACK: 'Revertido',

    // Oportunidades, pesquisa e enriquecimento
    CAPTURED: 'Para analisar',
    REVIEW: 'Para analisar',
    REVIEW_REQUIRED: 'Revisão necessária',
    QUALIFIED: 'Qualificada',
    DISCARDED: 'Descartada',
    SENT_TO_CRM: 'Enviada ao CRM',
    IDENTIFIED: 'Identificada',
    MULTIPLE_CANDIDATES: 'Múltiplos candidatos',
    NOT_FOUND: 'Não encontrado',
    NO_CONTACT_FOUND: 'Nenhum contato encontrado',
    NO_CANDIDATE_FOUND: 'Nenhum candidato encontrado',
    WAITING_BRAND_IDENTIFICATION: 'Aguardando identificação da marca',
    LINKED_EXISTING: 'Vinculado a um registro existente',
    OPPORTUNITY_CREATED: 'Oportunidade criada',
    PROMOTED: 'Transformado em oportunidade',
    ENRICHED: 'Dados encontrados',
    PARTIAL: 'Resultado parcial',
    SUGGESTED: 'Sugerido',
    ACCEPTED: 'Aceito',
    REJECTED: 'Recusado',
    STALE: 'Desatualizado',
    VALID: 'Válido',
    INVALID: 'Inválido',
    RISKY: 'Requer atenção',
    UNVERIFIABLE: 'Não foi possível verificar',
    RETRY: 'Nova tentativa agendada',
};

const WORD_LABELS: Record<string, string> = {
    WAITING: 'aguardando',
    AWAITING: 'aguardando',
    PENDING: 'pendente',
    CONTRACT: 'contrato',
    SIGNATURE: 'assinatura',
    PAYMENT: 'pagamento',
    METHOD: 'forma',
    DOCUMENT: 'documento',
    DOCUMENTS: 'documentos',
    DOCS: 'documentação',
    REVIEW: 'revisão',
    REQUIRED: 'necessária',
    PROCESSING: 'processando',
    COMPLETED: 'concluído',
    FAILED: 'falhou',
    CANCELLED: 'cancelado',
    CANCELED: 'cancelado',
    ACTIVE: 'ativo',
    INACTIVE: 'inativo',
    READY: 'pronto',
    FILE: 'protocolar',
    UPLOADED: 'enviado',
    RECEIVED: 'recebido',
    CREATED: 'criado',
    UPDATED: 'atualizado',
    VALIDATION: 'validação',
    CONTACT: 'contato',
    CANDIDATE: 'candidato',
    CANDIDATES: 'candidatos',
    FOUND: 'encontrado',
    NO: 'nenhum',
    WITH: 'com',
    ERRORS: 'alertas',
    TO: 'para',
};

export const normalizeStatusCode = (value: unknown): string => String(value ?? '')
    .trim()
    .replace(/([a-z\d])([A-Z])/g, '$1_$2')
    .replace(/[\s-]+/g, '_')
    .toUpperCase();

export const formatStatusLabel = (value: unknown, emptyLabel = 'Não informado'): string => {
    const raw = String(value ?? '').trim();
    if (!raw) return emptyLabel;
    const normalized = normalizeStatusCode(raw);
    if (STATUS_LABELS[normalized]) return STATUS_LABELS[normalized];

    // Textos descritivos vindos do INPI já são próprios para exibição.
    if (/\s/.test(raw) && !raw.includes('_')) return raw;

    const words = normalized.split('_').filter(Boolean).map(word => WORD_LABELS[word] || word.toLocaleLowerCase('pt-BR'));
    const label = words.join(' ');
    return label ? `${label.charAt(0).toLocaleUpperCase('pt-BR')}${label.slice(1)}` : emptyLabel;
};
